export default [
  {
    id: 'com.kera.test.panelapp',
    name: 'Test',
    theme_color: '#5294E2',
    dark_color: '#393939',
    icon: 'mdi-android-studio',
    system: true,
    page: 'apps/com.kera.test/panelapp.html',
  },
  {
    id: 'com.kera.calendar.panelapp',
    name: 'Calendar',
    system: true,
    theme_color: '#f78b8b',
    dark_color: '#393939',
    icon: 'mdi-calendar-blank',
    page: 'apps/com.kera.calendar/panelapp/index.html',
  },

  {
    id: 'com.kera.calculator.panelapp',
    name: 'Calculator',
    system: true,
    theme_color: '#ff9c59',
    dark_color: '#393939',
    icon: 'mdi-calculator-variant',
    page: 'apps/com.kera.calculator/index.html',
  },

  {
    id: 'com.kera.clipboard.panelapp',
    name: 'Clipboard',
    system: true,
    theme_color: '#e3bc6f',
    dark_color: '#393939',
    icon: 'mdi-clipboard-outline',
    page: 'apps/com.kera.clipboard/index.html',
  },

  {
    id: 'com.kera.finance.panelapp',
    name: 'Finance',
    system: true,
    theme_color: '#6bdb6b',
    dark_color: '#393939',
    icon: 'mdi-finance',
    page: 'apps/com.kera.finance/index.html',
  },

  {
    id: 'com.kera.translate.panelapp',
    name: 'Translate',
    theme_color: '#b1d170',
    dark_color: '#393939',
    icon: 'mdi-translate',
    page: 'https://translate.google.com/',
  },

  {
    id: 'com.kera.weather.panelapp',
    name: 'Weather',
    system: true,
    theme_color: '#2aa9f9',
    dark_color: '#393939',
    icon: 'mdi-weather-partly-snowy-rainy',
    page: 'apps/com.kera.weather/index.html',
  },

  {
    id: 'com.kera.notes.panelapp',
    name: 'Notes',
    system: true,
    theme_color: '#ffdc6d',
    dark_color: '#393939',
    icon: 'mdi-notebook',
    page: 'apps/com.kera.notes/index.html',
  },

  {
    id: 'https://messages.google.com/web/',
    name: 'Messages',
    theme_color: '#5d90fd',
    dark_color: '#104091',
    icon: 'mdi-message-text',
    page: 'https://messages.google.com/web/',
  },

  {
    id: 'https://web.telegram.org/',
    name: 'Telegram',
    theme_color: '#44a9e7',
    dark_color: '#1a232c',
    icon: 'resources/other/telegram.svg',
    page: 'https://web.telegram.org/',
  },
  {
    id: 'com.kera.homeassistant.panelapp',
    name: 'Home Assistant',
    system: true,
    theme_color: '#4bbff4',
    dark_color: '#1a232c',
    icon: 'resources/other/homeassistant.svg',
    page: 'apps/com.kera.homeassistant/index.html',
  },
  {
    id: 'com.expensive.mandala.panelapp',
    name: 'Mandala 3D',
    theme_color: '#cd4172',
    dark_color: '#151515',
    icon: 'mdi-octagram-outline',
    page: 'https://mandala.expensive.toys/',
  },
  {
    id: 'com.kera.clock.panelapp',
    name: 'Clock',
    system: true,
    theme_color: '#f43838',
    dark_color: '#393939',
    icon: 'mdi-clock',
    page: 'apps/com.kera.clock/index.html',
  },
  {
    id: 'com.kera.settings.panelapp',
    name: 'Settings',
    system: true,
    theme_color: '#58d2c6',
    dark_color: '#393939',
    icon: 'mdi-cog',
    page: 'apps/com.kera.settings/index.html',
  },
];
