export default [
  {
    name: 'locale',
    language: 'en',
    locale: 'en-IE',
    hour12: false,
  },

  {
    name: 'style',
    shell: 'Kera Eyecandy',
    shellList: ['Kera Basic', 'Kera Eyecandy'],
    ui: 'Kera Eyecandy',
    uiList: ['Kera Basic', 'Kera Eyecandy'],
    icon: 'Kera',
    iconList: ['Kera'],
    darkTheme: 'never',
    appSpecificTheme: true,
    animation: 'Kera Eyecandy',
    animationList: ['Kera Basic', 'Kera Eyecandy'],
    animationDuration: 250,
    taskbar_icon_size: 48,
    favorite_icon_size: 36,
    notifyPreviewTime: 4000,
    colorsFromWallpaper: true,
    blur: 10,
    borderRadius: 5,
    hotspotWidth: 2,
    color: {
      vibrant: '#3ac5b3',
      darkVibrant: '#193e6c',
      shellBackground: 'var(--kr-dark-vibrant)',
      shellBorder: 'var(--kr-vibrant)',
      shellText: '#f5f5f5',
      windowBackground: '#e6e6e6',
      windowBackgroundBlur: '#e6e6e6',
      windowTitle: '#212121',
      windowTitleBlur: '#212121',
      windowText: '#212121',
      windowTextBlur: '#424242',
      windowShadow: '0px 6px 50px 0px rgba(0,0,0,.6)',
      windowShadowBlur: '0 1px 3px rgba(0,0,0,.8)',
      generalBackground: '#f5f5f5',
      generalForeground: '#323232',
      generalText: '#212121',
      dark: {
        shellBackground: '#212121a1',
        shellBorder: '#193e6c',
        shellText: '#f5f5f5',
        windowBackground: '#212121',
        windowBackgroundBlur: '#000000',
        windowTitle: '#f5f5f5',
        windowTitleBlur: '#757575',
        windowText: '#f5f5f5',
        windowTextBlur: '#757575',
        generalBackground: '#393939',
        generalForeground: '#757575',
        generalText: '#f6f6f6',
      },
    },
    font: {
      general: 'PT Sans',
      title: 'Noto Sans',
      document: 'PT Sans',
      mono: 'deJaVu Sans Mono Book',
      generalSize: '14px',
      titleSize: '20px',
      documentSize: '14px',
      monoSize: '12px',
    },
    panel: {
      icon_size: 64,
      icon_number: 9,
    },
    area: {
      left: 'auto',
      right: 'auto',
      top: 'alwaysShow',
      bottom: 'auto',
      showFavorites: false,
    },
  },

  {
    name: 'background',
    type: 'image',
    image: {
      type: 'static',
      fit: 'center-cropped',
      selected: 0,
      list: [
        'resources/backgrounds/kera_cold_lights.webp',
        'resources/backgrounds/kera_dark_lights.webp',
        'resources/backgrounds/kera_warm_lights.webp',
        'resources/backgrounds/kera_palms_oil_evening.webp',
        'resources/backgrounds/kera_palms_oil_late_evening.webp',
        'resources/backgrounds/kera_palms_oil_night.webp',
        'resources/backgrounds/kera_palms_oil.webp',
        'resources/backgrounds/aditya-vyas-wmXVABZ7JBk-unsplash.webp',
        'resources/backgrounds/beach-bird-s-eye-view-daylight-1038374.webp',
        'resources/backgrounds/beautiful-bloom-blooming-768823.webp',
        'resources/backgrounds/blue-pink-abstract-ink-in-circles-picjumbo-com.webp',
        'resources/backgrounds/blue-umbrella-picjumbo-com.webp',
        'resources/backgrounds/boliviainteligente-xnl0PFy3euU-unsplash.webp',
        'resources/backgrounds/boliviainteligente-yzDtFEOnop8-unsplash.webp',
        'resources/backgrounds/chris-chondrogiannis-oN_rL__KiiU-unsplash.webp',
        'resources/backgrounds/cameron-gibson-wtLn23YbuTE-unsplash.webp',
        'resources/backgrounds/dark-plant-background-picjumbo-com.webp',
        'resources/backgrounds/foodiesfeed.com_blueberry-water-drop-close-up.webp',
        'resources/backgrounds/freenaturestock-2011.webp',
        'resources/backgrounds/freenaturestock-65.webp',
        'resources/backgrounds/freenaturestock-7.webp',
        'resources/backgrounds/howard-bouchevereau-BRDO4C-0h_s-unsplash.webp',
        'resources/backgrounds/jackson-jost-RMynbTjDu_g-unsplash.webp',
        'resources/backgrounds/marc-schulte-Xxf_Hsq62lA-unsplash.webp',
        'resources/backgrounds/markus-spiske-reDUEj_Bxug-unsplash.webp',
        'resources/backgrounds/pawel-czerwinski-1aMG_ShZCYg-unsplash.webp',
        'resources/backgrounds/pawel-czerwinski-fahoKISAg08-unsplash.webp',
        'resources/backgrounds/pawel-czerwinski-O9SoTdFD1gA-unsplash.webp',
        'resources/backgrounds/pawel-czerwinski-uARCs5MevTA-unsplash.webp',
        'resources/backgrounds/pexels-egor-kamelev-3220368.webp',
        'resources/backgrounds/primula-marginata-green-flower-picjumbo-com.webp',
        'resources/backgrounds/SplitShire-01052.webp',
        'resources/backgrounds/two-halloween-pumpkins-decorations-picjumbo-com.webp',
        'resources/backgrounds/vc5ovon3gzu-lydia-harper.webp',
        'resources/backgrounds/vishnu-mohanan-pfR18JNEMv8-unsplash.webp',
        'resources/backgrounds/yousef-espanioly-0iOOw41DZ28-unsplash.webp',
      ],
      thumbList: [
        'resources/backgrounds/thumbnails/kera_cold_lights.webp',
        'resources/backgrounds/thumbnails/kera_dark_lights.webp',
        'resources/backgrounds/thumbnails/kera_warm_lights.webp',
        'resources/backgrounds/thumbnails/kera_palms_oil_evening.webp',
        'resources/backgrounds/thumbnails/kera_palms_oil_late_evening.webp',
        'resources/backgrounds/thumbnails/kera_palms_oil_night.webp',
        'resources/backgrounds/thumbnails/kera_palms_oil.webp',
        'resources/backgrounds/thumbnails/aditya-vyas-wmXVABZ7JBk-unsplash.webp',
        'resources/backgrounds/thumbnails/beach-bird-s-eye-view-daylight-1038374.webp',
        'resources/backgrounds/thumbnails/beautiful-bloom-blooming-768823.webp',
        'resources/backgrounds/thumbnails/blue-pink-abstract-ink-in-circles-picjumbo-com.webp',
        'resources/backgrounds/thumbnails/blue-umbrella-picjumbo-com.webp',
        'resources/backgrounds/thumbnails/boliviainteligente-xnl0PFy3euU-unsplash.webp',
        'resources/backgrounds/thumbnails/boliviainteligente-yzDtFEOnop8-unsplash.webp',
        'resources/backgrounds/thumbnails/chris-chondrogiannis-oN_rL__KiiU-unsplash.webp',
        'resources/backgrounds/thumbnails/cameron-gibson-wtLn23YbuTE-unsplash.webp',
        'resources/backgrounds/thumbnails/dark-plant-background-picjumbo-com.webp',
        'resources/backgrounds/thumbnails/foodiesfeed.com_blueberry-water-drop-close-up.webp',
        'resources/backgrounds/thumbnails/freenaturestock-2011.webp',
        'resources/backgrounds/thumbnails/freenaturestock-65.webp',
        'resources/backgrounds/thumbnails/freenaturestock-7.webp',
        'resources/backgrounds/thumbnails/howard-bouchevereau-BRDO4C-0h_s-unsplash.webp',
        'resources/backgrounds/thumbnails/jackson-jost-RMynbTjDu_g-unsplash.webp',
        'resources/backgrounds/thumbnails/marc-schulte-Xxf_Hsq62lA-unsplash.webp',
        'resources/backgrounds/thumbnails/markus-spiske-reDUEj_Bxug-unsplash.webp',
        'resources/backgrounds/thumbnails/pawel-czerwinski-1aMG_ShZCYg-unsplash.webp',
        'resources/backgrounds/thumbnails/pawel-czerwinski-fahoKISAg08-unsplash.webp',
        'resources/backgrounds/thumbnails/pawel-czerwinski-O9SoTdFD1gA-unsplash.webp',
        'resources/backgrounds/thumbnails/pawel-czerwinski-uARCs5MevTA-unsplash.webp',
        'resources/backgrounds/thumbnails/pexels-egor-kamelev-3220368.webp',
        'resources/backgrounds/thumbnails/primula-marginata-green-flower-picjumbo-com.webp',
        'resources/backgrounds/thumbnails/SplitShire-01052.webp',
        'resources/backgrounds/thumbnails/two-halloween-pumpkins-decorations-picjumbo-com.webp',
        'resources/backgrounds/thumbnails/vc5ovon3gzu-lydia-harper.webp',
        'resources/backgrounds/thumbnails/vishnu-mohanan-pfR18JNEMv8-unsplash.webp',
        'resources/backgrounds/thumbnails/yousef-espanioly-0iOOw41DZ28-unsplash.webp',
      ],
    },
    brightness: 1,
    contrast: 1,
    blur: 0,
    blur_only_window: true,
  },

  {
    name: 'power',
    profile: 'balanced',
    onac: {
      screen_off: 600000,
      sleep: -1,
    },
    onbat: {
      screen_off: 120000,
      sleep: 600000,
    },
  },

  {
    name: 'a11y',
    screen_reader: false,
    screen_keyboard: false,
    screen_magnifier: false,
    bounce_keys: false,
    mouse_keys: false,
    sticky_keys: false,
    slow_keys: false,
    high_constast: false,
    auto_click: false,
    switch_access: false,
    voice_control: false,
    camera_control: false,
    motion_sickness: false,
    mono_audio: false,
    captions: false,
    motion_control: false,
    braille: false,
  },
];
